<x-public-layout title="トップ"><h1 class="my-5 text-3xl font-bold">{{ app(\App\Support\SiteSettings::class)->get('site.title','POL Community') }}</h1><p class="mb-5">{{ app(\App\Support\SiteSettings::class)->get('site.description','') }}</p>
@if($header)<img class="mb-6 max-h-80 w-full rounded object-cover" src="{{ route('images.show',$header->attachment_id) }}" alt="{{ $header->alt_text }}">@endif
<x-banners :banners="$banners->where('placement','home_header')" />
<div class="grid gap-8 lg:grid-cols-3"><div class="space-y-8 lg:col-span-2">
<section><h2 class="mb-3 text-xl font-bold">サイト更新情報</h2><ul class="space-y-3">@forelse($announcements as $item)<li><a class="underline" href="{{ route('announcements.show',$item->id) }}">{{ $item->title }}</a><p class="text-sm">{{ $item->summary }}</p></li>@empty<li>更新情報はありません。</li>@endforelse</ul></section>
<section><h2 class="mb-3 text-xl font-bold">メンバー日記</h2><ul class="space-y-3">@forelse($diaries as $item)<li><a class="underline" href="{{ route('diaries.show',$item->id) }}">{{ $item->title }}</a><p class="text-sm">{{ $item->excerpt }}</p></li>@empty<li>日記はまだありません。</li>@endforelse</ul></section>
<section><h2 class="mb-3 text-xl font-bold">コミュニティの新着</h2><ul class="space-y-3">@forelse($threads as $item)<li><a class="underline" href="{{ route('community.show',$item->id) }}">{{ $item->title }}</a> · {{ $item->post_count }}投稿</li>@empty<li>投稿はまだありません。</li>@endforelse</ul></section>
<section><h2 class="mb-3 text-xl font-bold">外部RSS</h2><ul class="space-y-4">@forelse($feeds as $item)<li>@if(app(\App\Support\MediaUrl::class)->https($item->url))<a class="underline" href="{{ $item->url }}" rel="noopener noreferrer" target="_blank">{{ $item->title }}</a>@else{{ $item->title }}@endif<p class="text-xs">{{ $item->source_name }} · {{ $item->published_at }}</p><div class="rich-text-content">{!! app(\App\Support\ContentSanitizer::class)->sanitize($item->summary_html ?? '') !!}</div></li>@empty<li>RSSはまだ取得されていません。</li>@endforelse</ul></section>
</div><aside><x-banners :banners="$banners->where('placement','home_sidebar')" /></aside></div><x-banners :banners="$banners->where('placement','home_footer')" /></x-public-layout>
