@php($headerEnabled=app(\App\Support\SiteSettings::class)->boolean('home.header_enabled',true))
<x-public-layout title="トップ">@if($headerEnabled&&!$header)<h1 class="my-5 text-3xl font-bold">{{ app(\App\Support\SiteSettings::class)->get('site.title','POL Community') }}</h1>@endif<p class="mb-5">{{ app(\App\Support\SiteSettings::class)->get('site.description','') }}</p>
@if($headerEnabled&&$header)<img class="mb-6 h-auto max-w-full rounded" src="{{ route('images.show',$header->attachment_id) }}" alt="{{ app(\App\Support\SiteSettings::class)->get('site.title','POL Community') }}">@endif
<x-banners :banners="$banners->where('placement','home_header')" align="center" /><div class="grid gap-8 lg:grid-cols-3"><div class="space-y-8 lg:col-span-2">
@foreach($sections as $section) @switch($section)
@case('announcements')<section><h2 class="mb-3 text-xl font-bold">{{ app(\App\Support\SiteSettings::class)->get('home.heading.announcements','サイト更新情報') }}</h2><ul class="space-y-3">@forelse($announcements as $item)<li>[{{ \Illuminate\Support\Carbon::parse($item->published_at)->format('Y-m-d') }}] <a class="underline" href="{{ route('announcements.show',$item->id) }}">{{ $item->title }}</a></li>@empty<li>更新情報はありません。</li>@endforelse</ul></section>@break
@case('diaries')<section><h2 class="mb-3 text-xl font-bold">{{ app(\App\Support\SiteSettings::class)->get('home.heading.diaries','メンバー日記') }}</h2><ul class="space-y-3">@forelse($diaries as $item)<li>[{{ \Illuminate\Support\Carbon::parse($item->published_at)->format('Y-m-d') }}] <a class="underline" href="{{ route('diaries.show',$item->id) }}">{{ $item->title }}</a> - {{ $item->author_name }}</li>@empty<li>日記はまだありません。</li>@endforelse</ul></section>@break
@case('community')<section><h2 class="mb-3 text-xl font-bold">{{ app(\App\Support\SiteSettings::class)->get('home.heading.community','コミュニティの新着') }}</h2><ul class="space-y-3">@forelse($threads as $item)<li>[{{ \Illuminate\Support\Carbon::parse($item->last_posted_at)->format('Y-m-d') }}] <a class="underline" href="{{ route('community.show',$item->id) }}">{{ $item->post_count>1?$item->title.' への返信':$item->title }}</a> - {{ $item->latest_author ?? '削除済みユーザー' }}</li>@empty<li>投稿はまだありません。</li>@endforelse</ul></section>@break
@case('feeds')<section><h2 class="mb-3 text-xl font-bold">{{ app(\App\Support\SiteSettings::class)->get('home.heading.feeds','外部RSS') }}</h2><ul class="space-y-4">@forelse($feeds as $item)<li>@if(app(\App\Support\MediaUrl::class)->https($item->url))<a class="underline" href="{{ $item->url }}" rel="noopener noreferrer" target="_blank">{{ $item->title }}</a>@else{{ $item->title }}@endif<p class="text-xs">{{ $item->source_name }} · {{ $item->published_at }}</p><div class="rich-text-content">{!! app(\App\Support\ContentSanitizer::class)->sanitize($item->summary_html ?? '') !!}</div></li>@empty<li>RSSはまだ取得されていません。</li>@endforelse</ul></section>@break
@endswitch @endforeach</div><aside><x-banners :banners="$banners->where('placement','home_sidebar')" align="right" /></aside></div><x-banners :banners="$banners->where('placement','home_footer')" align="center" /></x-public-layout>
