<x-layouts::app title="投稿検索"><main class="p-6"><h1 class="mb-4 text-2xl font-semibold">投稿検索</h1>@include('admin._nav')
<form class="mb-5 space-y-4 rounded border p-4" method="GET">
<div class="grid gap-3 md:grid-cols-3" data-search-row="text">@foreach([['type','種類'],['title','タイトル'],['author','投稿者']] as [$name,$label])<label>{{ $label }}@if($name==='type')<select class="mt-1 w-full rounded border p-2" name="type"><option value="">全種類</option>@foreach(['diary'=>'日記','thread'=>'スレッド','reply'=>'返信'] as $v=>$text)<option value="{{ $v }}" @selected(request('type')===$v)>{{ $text }}</option>@endforeach</select>@else<input class="mt-1 w-full rounded border p-2" name="{{ $name }}" value="{{ request($name) }}">@endif</label>@endforeach</div>
<div class="flex flex-wrap items-center gap-3" data-search-row="created"><label class="flex items-center gap-2 whitespace-nowrap">投稿日（開始）<input class="w-44 rounded border p-2" type="date" name="created_from" value="{{ request('created_from') }}"></label><span aria-hidden="true">～</span><label class="flex items-center gap-2 whitespace-nowrap">投稿日（終了）<input class="w-44 rounded border p-2" type="date" name="created_to" value="{{ request('created_to') }}"></label></div>
<div class="flex flex-wrap items-center gap-3" data-search-row="updated"><label class="flex items-center gap-2 whitespace-nowrap">更新日（開始）<input class="w-44 rounded border p-2" type="date" name="updated_from" value="{{ request('updated_from') }}"></label><span aria-hidden="true">～</span><label class="flex items-center gap-2 whitespace-nowrap">更新日（終了）<input class="w-44 rounded border p-2" type="date" name="updated_to" value="{{ request('updated_to') }}"></label></div>
<div class="flex gap-3" data-search-row="actions"><button class="w-[120px] rounded bg-zinc-900 px-5 py-2 text-white">検索</button><a class="w-[120px] rounded border px-5 py-2 text-center" href="{{ route('admin.content') }}">クリア</a></div>
</form>
@php($sortUrl=function($sort){$direction=request('sort','updated_at')===$sort&&request('direction','desc')==='asc'?'desc':'asc';return request()->fullUrlWithQuery(['sort'=>$sort,'direction'=>$direction,'page'=>null]);})
<form method="POST" action="{{ route('admin.content.destroy') }}" onsubmit="return confirm('選択した投稿を削除しますか？')">@csrf @method('DELETE')<div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead><tr><th class="p-2"><input id="select-all-items" type="checkbox" aria-label="一覧の投稿をすべて選択"></th>@foreach(['type'=>'種類','title'=>'タイトル','author'=>'投稿者','created_at'=>'投稿日','updated_at'=>'更新日'] as $sort=>$label)<th><a class="whitespace-nowrap underline" href="{{ $sortUrl($sort) }}">{{ $label }} @if(request('sort','updated_at')===$sort){{ request('direction','desc')==='asc'?'▲':'▼' }}@endif</a></th>@endforeach</tr></thead><tbody>@foreach($items as $item)<tr class="border-t"><td class="p-2"><input class="content-item-checkbox" type="checkbox" name="items[]" value="{{ $item->type }}:{{ $item->id }}"></td><td>{{ $item->type }}</td><td>{{ $item->type==='reply'?'「'.$item->title.'」への返信':$item->title }}</td><td>{{ $item->author }}</td><td>{{ $item->created_at }}</td><td>{{ $item->updated_at }}</td></tr>@endforeach</tbody></table></div><button class="mt-3 rounded bg-red-700 px-4 py-2 text-white">選択項目を削除</button></form><script>document.getElementById('select-all-items').addEventListener('change',event=>document.querySelectorAll('.content-item-checkbox').forEach(checkbox=>checkbox.checked=event.target.checked));</script>{{ $items->links() }}</main></x-layouts::app>
