<x-layouts::app :title="$character ? 'キャラクター編集' : 'キャラクター登録'"><div class="max-w-5xl p-6"><h1 class="mb-6 text-2xl font-semibold">{{ $character ? 'キャラクター編集' : 'キャラクター登録' }}</h1>
@if($errors->any())<div class="mb-4 rounded bg-red-50 p-3 text-red-900"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ $character ? route('characters.update',$character) : route('characters.store') }}" class="space-y-6">@csrf @if($character)@method('PUT')@endif
<section class="grid gap-4 rounded border p-4 md:grid-cols-2"><label>キャラクター名<input class="mt-1 w-full rounded border p-2" name="name" maxlength="100" value="{{ old('name',$character?->name) }}" required></label><label>公開範囲<select class="mt-1 w-full rounded border p-2" name="visibility">@foreach(['public'=>'公開','members'=>'メンバーのみ','private'=>'非公開'] as $v=>$label)<option value="{{ $v }}" @selected(old('visibility',$character?->visibility ?? 'public')===$v)>{{ $label }}</option>@endforeach</select></label><label class="flex items-center gap-2"><input type="hidden" name="is_primary" value="0"><input type="checkbox" name="is_primary" value="1" @checked(old('is_primary',$character?->is_primary))>主キャラクターにする</label><label class="md:col-span-2">紹介<textarea class="mt-1 w-full rounded border p-2" name="profile_text" rows="5">{{ old('profile_text',$character?->profile_text) }}</textarea></label></section>
@php($selects=['world_id'=>['ワールド',$worlds],'nation_id'=>['所属国',$nations],'race_id'=>['種族',$races],'main_job_id'=>['メインジョブ',$jobs],'support_job_id'=>['サポートジョブ',$jobs]])
<section class="grid gap-4 rounded border p-4 md:grid-cols-3"><h2 class="text-lg font-medium md:col-span-3">FFXIプロフィール</h2>@foreach($selects as $name=>[$label,$items])<label>{{ $label }}<select class="mt-1 w-full rounded border p-2" name="{{ $name }}"><option value="">未設定</option>@foreach($items as $item)<option value="{{ $item->id }}" @selected((string)old($name,$profile?->$name)===(string)$item->id)>{{ $item->name_ja }}</option>@endforeach</select></label>@endforeach<label>フェイスタイプ<select class="mt-1 w-full rounded border p-2" name="face_type_id"><option value="">未設定</option>@foreach($faces as $face)<option value="{{ $face->id }}" data-race="{{ $face->race_id }}" @selected((string)old('face_type_id',$profile?->face_type_id)===(string)$face->id)>{{ $face->name_ja }}</option>@endforeach</select></label><label>ランク<input class="mt-1 w-full rounded border p-2" type="number" min="0" max="10" name="rank" value="{{ old('rank',$profile?->rank) }}"></label><label>POLハンドル<input class="mt-1 w-full rounded border p-2" name="pol_handle" maxlength="64" value="{{ old('pol_handle',$profile?->pol_handle) }}"></label></section>
<section class="rounded border p-4"><h2 class="mb-3 text-lg font-medium">ジョブレベル</h2><div class="grid grid-cols-2 gap-3 md:grid-cols-4 lg:grid-cols-6">@foreach($jobs as $job)<label class="text-sm">{{ $job->name_ja }}<input class="mt-1 w-full rounded border p-2" type="number" min="0" max="99" name="job_levels[{{ $job->id }}]" value="{{ old('job_levels.'.$job->id,$jobLevels[$job->id] ?? '') }}"></label>@endforeach</div></section>
<section class="rounded border p-4"><h2 class="mb-3 text-lg font-medium">合成スキル</h2><div class="grid grid-cols-2 gap-3 md:grid-cols-5">@foreach($crafts as $craft)<label class="text-sm">{{ $craft->name_ja }}<input class="mt-1 w-full rounded border p-2" type="number" min="0" max="999" name="craft_levels[{{ $craft->id }}]" value="{{ old('craft_levels.'.$craft->id,$craftLevels[$craft->id] ?? '') }}"></label>@endforeach</div></section>
<button class="rounded bg-zinc-900 px-5 py-2 text-white">保存</button></form>
@if($character)<form class="mt-8" method="POST" action="{{ route('characters.destroy',$character) }}" onsubmit="return confirm('削除しますか？')">@csrf @method('DELETE')<button class="text-red-700 underline">このキャラクターを削除</button></form>@endif</div></x-layouts::app>
