<x-layouts::app :title="$diary ? '日記編集' : '日記を書く'"><div class="max-w-5xl p-6"><h1 class="mb-6 text-2xl font-semibold">{{ $diary ? '日記編集' : '日記を書く' }}</h1>
@if($errors->any())<div class="mb-4 rounded bg-red-50 p-3 text-red-900"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" enctype="multipart/form-data" action="{{ $diary ? route('diaries.update',$diary) : route('diaries.store') }}" class="space-y-5">@csrf @if($diary)@method('PUT')@endif
<label class="block">タイトル<input class="mt-1 w-full rounded border p-2" name="title" maxlength="200" value="{{ old('title',$diary?->title) }}" required></label>
<div><span class="mb-1 block">本文</span><x-rich-text-editor name="body_html" :value="old('body_html',$diary?->body_html ?? '')" /></div>
<x-media-fields />
<div class="grid gap-4 md:grid-cols-3"><label>キャラクター<select class="mt-1 w-full rounded border p-2" name="character_id"><option value="">指定なし</option>@foreach($characters as $character)<option value="{{ $character->id }}" @selected(old('character_id',$diary?->character_id ?? request('character_id'))===$character->id)>{{ $character->name }}</option>@endforeach</select></label><label>公開範囲<select class="mt-1 w-full rounded border p-2" name="visibility">@foreach(['public'=>'公開','members'=>'メンバーのみ','private'=>'非公開'] as $v=>$label)<option value="{{ $v }}" @selected(old('visibility',$diary?->visibility ?? 'public')===$v)>{{ $label }}</option>@endforeach</select></label><label>状態<select class="mt-1 w-full rounded border p-2" name="status">@foreach(['draft'=>'下書き','published'=>'公開','archived'=>'アーカイブ'] as $v=>$label)<option value="{{ $v }}" @selected(old('status',$diary?->status ?? 'draft')===$v)>{{ $label }}</option>@endforeach</select></label></div>
<fieldset><legend>カテゴリ</legend><div class="flex flex-wrap gap-4">@foreach($categories as $category)<label><input type="checkbox" name="category_ids[]" value="{{ $category->id }}" @checked(in_array($category->id,old('category_ids',$selectedCategories)))> {{ $category->name }}</label>@endforeach</div></fieldset><label class="block">タグ（カンマ区切り、最大10件）<input class="mt-1 w-full rounded border p-2" name="tags" value="{{ old('tags',$tagText) }}"></label><label><input type="hidden" name="comments_enabled" value="0"><input type="checkbox" name="comments_enabled" value="1" @checked(old('comments_enabled',$diary?->comments_enabled ?? true))> コメントを許可</label>@if($diary)<x-preserve-updated-at />@endif<div class="flex gap-3"><button class="rounded bg-zinc-900 px-5 py-2 text-white">保存</button><a class="rounded border px-5 py-2" href="{{ $diary ? route('diaries.show', $diary) : route('diaries.index') }}" onclick="return confirm('入力内容は保存されません。キャンセルしますか？')">キャンセル</a></div></form>
@if($diary)<form class="mt-8" method="POST" action="{{ route('diaries.destroy',$diary) }}" onsubmit="return confirm('削除しますか？')">@csrf @method('DELETE')<button class="rounded border border-red-700 px-3 py-2 text-red-700">この日記を削除</button></form>@endif</div></x-layouts::app>
